<a href="https://colab.research.google.com/github/PRATHAM987654321/Python-Programming/blob/main/Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MY FIRST PROGRAM**

In [ ]:
a="I am Pratham"
print(a)
print(a[5])


I am Pratham
P


Variable Declearation

In [ ]:
a=5
b=8
sum=a+b
print("The sum of ",a ,"and" ,b,"is",sum )

The sum of  5 and 8 is 13


**Assignment**

**1: Subtraction of 3 numbers**


In [ ]:
a=12
b=15
c=21
diff=a-b-c
print("The diff between a and b",a,"and",b,"is",diff)

The diff between a and b 12 and 15 is -24


**2: Division of numbers**

In [ ]:
a=12
b=6
quotient=a/b
remainder=a%b
print("The quotient of 2 numbers",a,"and",b,"is",quotient)
print("The quotient of 2 numbers",a,"and",b,"is",remainder)

The quotient of 2 numbers 12 and 6 is 2.0
The quotient of 2 numbers 12 and 6 is 0


**3: Squaring and Square Root**

In [ ]:
import math
p=12
q=25
sq=p*p
sqrt=math.sqrt(q)
print("The square of the number",p,"is",sq)
print("The square root of the number",q,"is",sqrt)
a=5
b=3j
z=a+b
print("The complex number is",z)
type(z)


The square of the number 12 is 144
The square root of the number 25 is 5.0
The complex number is (5+3j)


complex

**List**

In [ ]:
lis=['kau','aaa','bdf','fgt']
lis1=['aaa','xsw','swa']
lis.sort()
lis
lis.append("lop")
lis
lis2=lis+lis1
print(len(lis2))


8


**Tuples**

In [ ]:
tup=("Hubli","blore","belgaum")
print(type(tup))
tup1=('kashmir','lahore')
tup2=tup+tup1
tup2
print(tup2[0])
print(tup2[-1])
y=tup2.index("blore")
print(y)

<class 'tuple'>
Hubli
lahore
1


**Sets**

In [ ]:
set1={"red","blue","yellow","orange"}
print(set1)
set1.add("green")
set1

{'yellow', 'blue', 'orange', 'red'}


{'blue', 'green', 'orange', 'red', 'yellow'}

**Dictionary**

In [ ]:
dict1={"Name":"Kaushik","age ":"32"}
dict2=dict(Name="pratham")
dict2

{'Name': 'pratham'}

**Bitwise Operator**

In [ ]:
print(8 & 12)
print(8 | 12)
print(8 ^ 12)
a=12
a+=3
print(a)
b=16
b-=2
print(b)

8
12
4
15
14


**Identify and Membership Operator**

In [ ]:
x=['Hubli','Blore']
y=['Hubli','Blore']
z=x
x=y
z=x
print(z is x)
print(y is x)


True
True


**Looping Statements**

In [ ]:
for num  in range(6):
 print(num)

0
1
2
3
4
5


**Numpy array**

In [ ]:
# Random number array
import numpy as np
n1=np.random.randint(100,500,10)
n1

array([158, 229, 299, 233, 153, 277, 399, 117, 380, 241])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
print(np.hstack((n1,n2)))


[10 20 30 40 50 60]
[50 70 90]


In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([30,40,60])
np.intersect1d(n1,n2)

array([30])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([30,40,60])
np.setdiff1d(n2,n1)

array([40, 60])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([30,40,60])
np.mean([n1])


20.0

In [ ]:
import pandas as pd
li=['a','b','c',1,2,3]
s1=pd.Series(li)
s1

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [ ]:
import random
gamelist=['snake','water','fire']
z=random.choice(gamelist)
print("enter either the snake,water,fire")
print(user)
if(computer=='snake'and user=='fire'):
  print("user won")
elif(computer=='snake'and user=='water'):
  print("computer won")
elif(computer=='water'and user=='fire'):
  print("computer won")
elif(computer=='water'and user=='snake'):
  print("user win")
elif(computer=='fire'and user=='water'):
  print("user win")
elif()


